### DISCUSSION TITLE
To those wanting to use HTTP and/or HTTPS

### DISCUSSION THREAD

**Discussion by LexiBigCheese** [rust3ds/ctru-rs#209] [General]
You'll want to comment out the assertion that causes issue #174 to have a panic, then cargo clean so cargo rebuilds std with this change.
~~Then, patch the `ring` crate to be the one I'm trying to get pulled into the main branch,~~
EDIT: It has been pulled!
EDIT2: Note: Point at ring's main branch.
```toml
[patch.crates-io]
ring = {git = "https://github.com/briansmith/ring"}
```
and ensure
```toml
[profile.dev.package.ring]
opt-level = 1
[profile.release.package.ring]
opt-level = 1
```
Note that `patch` and `profile` sections go in `Cargo.toml`, if you're using a cargo workspace, it does in the workspace's `Cargo.toml`
Additionally, you'll want the environment variable
```sh
export CFLAGS_armv6k_nintendo_3ds="-march=armv6k -mfloat-abi=hard -finline-limit=100000"
```
And now, the `minreq` crate will now let you do https.
Having a timeout may be that which causes the `ureq` crate to fail, I've been told to look into yielding when listening on an `mpsc::Receiver`, but I'm not that great at modifying `std`, so instead I just modified and patched `ehttp` to use `minreq` on `cfg(target_os = "horizon")`
